### ISSUE TITLE
Getting Role Errors with different Models / Tasks

### ISSUE THREAD

**Issue by ghost** [philschmid/cdk-samples#2] opened 2022-01-17 16:17 UTC
Hey, i love your examples and the way you described them and everything is working as intended.

But when i try different models (with this example: https://github.com/philschmid/cdk-samples/tree/master/aws-lambda-sagemaker-endpoint-huggingface)  

`$ cdk deploy \
  -c model="setu4993/LaBSE" \
  -c task="feature-extraction"\`

I am there seems to be some issue with the new role created / assumed. From a sagemaker notebook I can call the Endpoint. But a curl request to the api is denied.

`{"error": "ClientError('An error occurred (AccessDeniedException) when calling the InvokeEndpoint operation: User: arn:aws:sts::232372787505:assumed-role/HuggingfaceSagemakerEndpo-sminvokeServiceRole2D430-4WHEQWWK3WXH/HuggingfaceSagemakerEndpoint-sminvokeE2871326-Oc5R37D63bAz is not authorized to perform: sagemaker:InvokeEndpoint on resource: arn:aws:sagemaker:eu-central-1:232372787505:endpoint/endpoint-setu4993--labse because no identity-based policy allows the sagemaker:InvokeEndpoint action')"}%`

**Comment by philschmid** [comment] 2022-01-17 16:21
I could you please re-pull master again? I committed a change. 
https://github.com/philschmid/cdk-samples/commit/b3c85cf6cdd1b95a5e5929a3f62296b7bf5c0b77

I think the issue is casing. Your AWS Lambda might have in its permission policy document cased name `LaBSE` but the endpoint is always lower. I already fixed that for another sample.

**Comment by ghost** [comment] 2022-01-17 16:35
Did re-pull master and it works like a charm! Thanks for the super fast help, your examples are extremely helpful to me!

**Closed as completed** 2022-01-17 16:35 UTC

**Comment by philschmid** [comment] 2022-01-17 17:03
Your welcome! thanks for flagging!
